"""Synchronize README tables with the latest reproduced notebook outputs."""

from __future__ import annotations

import json
import re
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
README_PATH = ROOT / "README.md"
METRICS_PATH = ROOT / "data" / "reproduced" / "metrics.json"
BANDS_PATH = ROOT / "data" / "reproduced" / "score_band_analysis.csv"


def replace_block(text: str, start: str, end: str, content: str) -> str:
    pattern = re.compile(
        rf"{re.escape(start)}.*?{re.escape(end)}",
        flags=re.DOTALL,
    )
    replacement = f"{start}\n{content.rstrip()}\n{end}"
    updated, count = pattern.subn(replacement, text, count=1)
    if count != 1:
        raise ValueError(f"README marker block not found: {start}")
    return updated


def interval_upper(value: str) -> float:
    numbers = re.findall(r"-?\d+(?:\.\d+)?", str(value))
    if not numbers:
        raise ValueError(f"Cannot parse score band: {value}")
    return float(numbers[-1])


def main() -> None:
    metrics = json.loads(METRICS_PATH.read_text(encoding="utf-8"))
    bands = pd.read_csv(BANDS_PATH)
    bands["Upper_Bound"] = bands["Score_Band"].map(interval_upper)

    total_transactions = int(bands["Transactions"].sum())
    total_fraud = int(bands["Fraud_Count"].sum())
    intervention = bands[bands["Upper_Bound"] <= 500]
    intervention_transactions = int(intervention["Transactions"].sum())
    intervention_fraud = int(intervention["Fraud_Count"].sum())
    intervention_share = intervention_transactions / total_transactions * 100
    fraud_capture = intervention_fraud / total_fraud * 100

    metrics.update(
        {
            "test_transactions": total_transactions,
            "test_fraud_cases": total_fraud,
            "score_at_most_500_transactions": intervention_transactions,
            "score_at_most_500_fraud": intervention_fraud,
            "score_at_most_500_share_pct": intervention_share,
            "score_at_most_500_fraud_capture_pct": fraud_capture,
        }
    )
    METRICS_PATH.write_text(
        json.dumps(metrics, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    metrics_block = f"""
Results below are generated by the repository's automated GitHub Actions run
using the public ULB dataset and the committed modeling code.

| Metric | Reproduced result |
|---|---:|
| Test transactions | **{total_transactions:,}** |
| Fraud cases in test set | **{total_fraud:,}** |
| ROC-AUC | **{metrics['roc_auc']:.4f}** |
| KS statistic | **{metrics['ks']:.4f}** |
| Minimum score | **{metrics['score_min']:,}** |
| Median score | **{metrics['score_median']:.1f}** |
| Maximum score | **{metrics['score_max']:,}** |
| Transactions scoring ≤500 | **{intervention_share:.2f}%** ({intervention_transactions:,}) |
| Fraud captured at score ≤500 | **{fraud_capture:.2f}%** ({intervention_fraud:,}/{total_fraud:,}) |

Machine-readable results are stored in
[`data/reproduced/metrics.json`](data/reproduced/metrics.json).
"""

    band_rows = []
    for _, row in bands.iterrows():
        fraud_rate = row["Fraud_Rate"]
        rate_text = "—" if pd.isna(fraud_rate) else f"{fraud_rate:.2f}%"
        band_rows.append(
            f"| {row['Score_Band']} | {int(row['Transactions']):,} | "
            f"{int(row['Fraud_Count']):,} | {rate_text} |"
        )
    bands_block = """
The following table is regenerated from the current hold-out test set:

| Score band | Transactions | Fraud | Fraud rate |
|---|---:|---:|---:|
""" + "\n".join(band_rows) + f"""

With the current decision threshold, scores at or below 500 cover
**{intervention_share:.2f}%** of test transactions and capture
**{fraud_capture:.2f}%** of the fraud cases in the test set.

The complete table is stored in
[`data/reproduced/score_band_analysis.csv`](data/reproduced/score_band_analysis.csv).
"""

    readme = README_PATH.read_text(encoding="utf-8")
    readme = replace_block(
        readme,
        "<!-- REPRODUCED_METRICS_START -->",
        "<!-- REPRODUCED_METRICS_END -->",
        metrics_block,
    )
    readme = replace_block(
        readme,
        "<!-- REPRODUCED_BANDS_START -->",
        "<!-- REPRODUCED_BANDS_END -->",
        bands_block,
    )
    README_PATH.write_text(readme, encoding="utf-8")


if __name__ == "__main__":
    main()

